#!/bin/bash
set -e

echo "============================================"
echo "  GonoPBX Installer"
echo "============================================"
echo ""

# Check if user can run Docker (root or docker group)
if ! docker info >/dev/null 2>&1; then
    echo "ERROR: Cannot connect to Docker."
    echo "       Run as root or add your user to the docker group:"
    echo "       sudo usermod -aG docker \$USER"
    exit 1
fi

# Check prerequisites
command -v docker >/dev/null 2>&1 || { echo "ERROR: docker is not installed."; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "ERROR: docker compose is not available."; exit 1; }

echo "[OK] Docker and Docker Compose found."
echo ""

# Detect external IP
echo "Detecting external IP address..."
DETECTED_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || curl -s --max-time 5 icanhazip.com 2>/dev/null || echo "")

if [ -n "$DETECTED_IP" ]; then
    echo "Detected external IP: $DETECTED_IP"
    read -rp "Use this IP? [Y/n]: " USE_DETECTED
    if [ "$USE_DETECTED" = "n" ] || [ "$USE_DETECTED" = "N" ]; then
        read -rp "Enter external IP: " EXTERNAL_IP
    else
        EXTERNAL_IP="$DETECTED_IP"
    fi
else
    echo "Could not detect external IP automatically."
    read -rp "Enter external IP: " EXTERNAL_IP
fi

# Detect local LAN IP
LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "")

echo ""

# Network mode
echo "Nutzt du einen Reverse Proxy (z.B. Nginx) vor GonoPBX?"
echo "  [1] Nein  - Direkter Zugriff aus dem Netzwerk (empfohlen fuer Heimnetz)"
echo "  [2] Ja    - Zugriff nur ueber localhost/Reverse Proxy"
read -rp "Auswahl [1]: " PROXY_CHOICE
if [ "$PROXY_CHOICE" = "2" ]; then
    BIND_ADDRESS="127.0.0.1"
    echo "-> Bind: 127.0.0.1 (nur localhost)"
else
    BIND_ADDRESS="0.0.0.0"
    echo "-> Bind: 0.0.0.0 (Zugriff aus dem Netzwerk)"
fi

echo ""

# Admin password
read -rp "Set admin password (leave empty to auto-generate): " ADMIN_PASSWORD
if [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=' | head -c 20)
    echo "Generated admin password: $ADMIN_PASSWORD"
fi

# Generate secure random passwords
JWT_SECRET=$(openssl rand -base64 48 | tr -d '/+=')
DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')
AMI_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')

echo ""
echo "Generating configuration..."

# Create .env file
cat > .env <<EOF
# GonoPBX Configuration - generated by install.sh
EXTERNAL_IP=${EXTERNAL_IP}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
JWT_SECRET=${JWT_SECRET}
DB_PASSWORD=${DB_PASSWORD}
AMI_PASSWORD=${AMI_PASSWORD}
BIND_ADDRESS=${BIND_ADDRESS}
EOF

echo "[OK] .env created"

# Write manager.conf from template with generated AMI password
sed "s/%%AMI_PASSWORD%%/${AMI_PASSWORD}/" asterisk/config/manager.conf.template > asterisk/config/manager.conf

echo "[OK] manager.conf updated"

# Start containers
echo ""
echo "Starting containers..."
docker compose up -d --build

# Send anonymous install telemetry (non-blocking, no personal data)
INSTALL_OS=$(. /etc/os-release 2>/dev/null && echo "$ID $VERSION_ID" || echo "unknown")
INSTALL_ARCH=$(uname -m)
INSTALL_VERSION=$(grep '^VERSION' backend/version.py 2>/dev/null | cut -d'"' -f2 || echo "unknown")
curl -s -o /dev/null --max-time 5 \
  -X POST "https://analytics.gonopbx.de/api/send" \
  -H "Content-Type: application/json" \
  -H "User-Agent: GonoPBX-Installer/${INSTALL_VERSION}" \
  -d "{\"payload\":{\"hostname\":\"gonopbx.de\",\"url\":\"/install\",\"website\":\"cc8fa162-1aef-4c89-8e13-4fdbfa9bc6f7\",\"name\":\"install\",\"data\":{\"os\":\"${INSTALL_OS}\",\"arch\":\"${INSTALL_ARCH}\",\"version\":\"${INSTALL_VERSION}\"}}}" \
  2>/dev/null || true

echo ""
echo "============================================"
echo "  GonoPBX Installation Complete!"
echo "============================================"
echo ""
if [ "$BIND_ADDRESS" = "0.0.0.0" ]; then
    ACCESS_IP="${LOCAL_IP:-$EXTERNAL_IP}"
    echo "  Web GUI:    http://${ACCESS_IP}:3000"
    echo "  API:        http://${ACCESS_IP}:8000"
    if [ -n "$LOCAL_IP" ] && [ "$LOCAL_IP" != "$EXTERNAL_IP" ]; then
        echo ""
        echo "  Lokales Netzwerk: http://${LOCAL_IP}:3000"
        echo "  Extern:           http://${EXTERNAL_IP}:3000"
        echo "                     (Port 3000 muss im Router freigegeben sein)"
    fi
else
    echo "  Web GUI:    http://localhost:3000"
    echo "  API:        http://localhost:8000"
    echo "  (Reverse Proxy noetig fuer externen Zugriff)"
fi
echo ""
echo "  Login:      admin / ${ADMIN_PASSWORD}"
echo ""
echo "  Credentials are saved in .env"
echo "============================================"
